language: python

sudo: required
dist: trusty

python:
- 3.4

services:
- docker

virtualenv:
  # The PyQt5 install ends up amongst system packages
  system_site_packages: true

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- docker build -t pyblish/pyblish-qml .
- docker run --rm -v $(pwd):/pyblish-qml pyblish/pyblish-qml
