language: python
sudo: required
dist: trusty
python:
- 3.4

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

virtualenv:
  # The PyQt5 install ends up amongst system packages
  system_site_packages: true

install:
- sudo apt-get update
- sudo apt-get install -y python3-pyqt5 python3-pyqt5.qtquick
- pip install coverage nose
- git clone https://github.com/pyblish/pyblish-rpc
- git clone https://github.com/pyblish/pyblish-base
- export PYTHONPATH=$(pwd)/pyblish-rpc:$(pwd)/pyblish-base

script:
- python run_coverage.py

after_success:
- coveralls
