language: python
dist: trusty
python:
- 3.5

sudo: required # install.sh requires sudo apt-get

install:
- sudo apt-get update
- sudo apt-get install -y python3-pyqt5
- pip install coverage nose
- git clone https://github.com/pyblish/pyblish-rpc
- git clone https://github.com/pyblish/pyblish-base
- export PYTHONPATH=$(pwd)/pyblish-rpc:$(pwd)/pyblish-base

script:
- nosetests -c .noserc

after_success:
- coveralls
