language: python

python:
- 2.7

sudo: required # install.sh requires sudo apt-get on Linux

install:
- echo "Install.."
- source .travis/install_linux.sh
- source .travis/install.sh
- pip install coverage nose

script:
- nosetests -c .noserc

after_success:
- coveralls
